-- ...existing code...
-- Remove CREATE DATABASE and USE statements

CREATE TABLE Admins (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL
);

CREATE TABLE Students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    father_name VARCHAR2(50),
    username VARCHAR2(50) UNIQUE,
    password_hash VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Teachers (
    teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    username VARCHAR2(50) UNIQUE,
    password_hash VARCHAR2(255)
);

CREATE TABLE Courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR2(100),
    description CLOB
);

CREATE TABLE Classes (
    class_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR2(50),
    course_id NUMBER,
    teacher_id NUMBER,
    FOREIGN KEY (course_id) REFERENCES Courses(course_id),
    FOREIGN KEY (teacher_id) REFERENCES Teachers(teacher_id)
);

CREATE TABLE Enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER,
    class_id NUMBER,
    FOREIGN KEY (student_id) REFERENCES Students(student_id),
    FOREIGN KEY (class_id) REFERENCES Classes(class_id)
);

CREATE TABLE Grades (
    grade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER,
    grade FLOAT,
    comments CLOB,
    date_recorded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (enrollment_id) REFERENCES Enrollments(enrollment_id)
);

CREATE TABLE Notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100),
    content CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by NUMBER,
    FOREIGN KEY (created_by) REFERENCES Admins(admin_id)
);

CREATE TABLE Files (
    file_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR2(255),
    file_path VARCHAR2(255),
    file_type VARCHAR2(50),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uploaded_by NUMBER,
    FOREIGN KEY (uploaded_by) REFERENCES Admins(admin_id)
);

-- Sample data
INSERT INTO Admins (username, password_hash) VALUES ('admin', '123456');
INSERT INTO Teachers (first_name, last_name, username, password_hash) VALUES ('Γιώργος', 'Παπαδόπουλος', 'gpap', '123');
INSERT INTO Courses (course_name, description) VALUES ('Μαθηματικά', 'Μάθημα Μαθηματικών Α Λυκείου');
INSERT INTO Classes (class_name, course_id, teacher_id) VALUES ('Α1 Μαθηματικών', 1, 1);
INSERT INTO Students (first_name, last_name, father_name, username, password_hash) VALUES ('Μαρία', 'Ιωάννου', 'Νίκος', 'mariaio', '123');
INSERT INTO Enrollments (student_id, class_id) VALUES (1, 1);
INSERT INTO Grades (enrollment_id, grade, comments) VALUES (1, 18.5, 'Πολύ καλή πρόοδος');
-- ...existing code...