-- Remove CREATE DATABASE and USE statements (Oracle does not support them)

CREATE TABLE notes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(255) NOT NULL,
  contents CLOB NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO notes (title, contents)
VALUES 
('My First Note', 'A note about something');

INSERT INTO notes (title, contents)
VALUES 
('My Second Note', 'A note about something else');